package com.dony.api.matching.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.UUID;

public record BidResponse(
        UUID id,
        UUID announcementId,
        UUID senderId,
        String senderName,
        String senderPhone,
        BigDecimal weightKg,
        BigDecimal declaredValueEur,
        String description,
        String contentCategory,
        String recipientName,
        String recipientPhone,
        String status,
        String rejectionReason,
        String handoverLocation,
        LocalDateTime handoverWindowStart,
        LocalDateTime handoverWindowEnd,
        boolean voyageurConfirmed,
        LocalDateTime disclaimerSignedAt,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        String departureCity,
        String arrivalCity,
        LocalDate departureDate,
        LocalTime departureTime,
        LocalTime arrivalTime,
        BigDecimal pricePerKg,
        String trackingNumber,
        String trackingToken,
        String confirmationCode,
        UUID travelerId,
        String travelerName,
        String travelerPhone
) {}
